------------- create table --------------
CREATE TABLE admins (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username VARCHAR2(50) UNIQUE NOT NULL,
    password VARCHAR2(100) NOT NULL  -- (hashed in production)
);

CREATE TABLE students (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    full_name VARCHAR2(150),
    dob DATE,
    gender VARCHAR2(10),
    phone VARCHAR2(20),
    address VARCHAR2(255)
);

CREATE TABLE programs (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR2(100),
    description VARCHAR2(255),
    duration VARCHAR2(50)
);

CREATE TABLE enrollments (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    student_id NUMBER REFERENCES students(id),
    program_id NUMBER REFERENCES programs(id),
    enrollment_date DATE DEFAULT SYSDATE
);

------- create Package Spec ---------
CREATE OR REPLACE PACKAGE pkg_student_enroll AS
    -- Student + Enrollment
    PROCEDURE register_and_enroll(
        p_full_name   IN VARCHAR2,
        p_dob         IN DATE,
        p_gender      IN VARCHAR2,
        p_phone       IN VARCHAR2,
        p_address     IN VARCHAR2,
        p_program_id  IN NUMBER,
        p_enrollment_id OUT NUMBER
    );

    PROCEDURE get_enrollments(p_cursor OUT SYS_REFCURSOR);

    PROCEDURE update_student(
        p_student_id  IN NUMBER,
        p_full_name   IN VARCHAR2,
        p_dob         IN DATE,
        p_gender      IN VARCHAR2,
        p_phone       IN VARCHAR2,
        p_address     IN VARCHAR2
    );

    PROCEDURE delete_enrollment(p_enrollment_id IN NUMBER);

    -- Program Management
    PROCEDURE add_program(
        p_name        IN VARCHAR2,
        p_description IN VARCHAR2,
        p_duration    IN VARCHAR2,
        p_program_id  OUT NUMBER
    );

    PROCEDURE update_program(
        p_program_id  IN NUMBER,
        p_name        IN VARCHAR2,
        p_description IN VARCHAR2,
        p_duration    IN VARCHAR2
    );

    PROCEDURE delete_program(p_program_id IN NUMBER);

    PROCEDURE get_programs(p_cursor OUT SYS_REFCURSOR);

END pkg_student_enroll;
/

---------Package Body----------
CREATE OR REPLACE PACKAGE BODY pkg_student_enroll AS

    -- Register student + enroll
    PROCEDURE register_and_enroll(
        p_full_name   IN VARCHAR2,
        p_dob         IN DATE,
        p_gender      IN VARCHAR2,
        p_phone       IN VARCHAR2,
        p_address     IN VARCHAR2,
        p_program_id  IN NUMBER,
        p_enrollment_id OUT NUMBER
    ) AS
        v_student_id NUMBER;
    BEGIN
        INSERT INTO students(full_name, dob, gender, phone, address)
        VALUES (p_full_name, p_dob, p_gender, p_phone, p_address)
        RETURNING id INTO v_student_id;

        INSERT INTO enrollments(student_id, program_id)
        VALUES (v_student_id, p_program_id)
        RETURNING id INTO p_enrollment_id;
    END register_and_enroll;

    -- View enrollments
    PROCEDURE get_enrollments(p_cursor OUT SYS_REFCURSOR) AS
    BEGIN
        OPEN p_cursor FOR
            SELECT e.id AS enrollment_id,
                   s.id AS student_id,
                   s.full_name,
                   p.name AS program,
                   e.enrollment_date
            FROM enrollments e
            JOIN students s ON e.student_id = s.id
            JOIN programs p ON e.program_id = p.id
            ORDER BY e.enrollment_date DESC;
    END get_enrollments;

    -- Update student info
    PROCEDURE update_student(
        p_student_id  IN NUMBER,
        p_full_name   IN VARCHAR2,
        p_dob         IN DATE,
        p_gender      IN VARCHAR2,
        p_phone       IN VARCHAR2,
        p_address     IN VARCHAR2
    ) AS
    BEGIN
        UPDATE students
        SET full_name = p_full_name,
            dob       = p_dob,
            gender    = p_gender,
            phone     = p_phone,
            address   = p_address
        WHERE id = p_student_id;
    END update_student;

    -- Delete enrollment
    PROCEDURE delete_enrollment(p_enrollment_id IN NUMBER) AS
    BEGIN
        DELETE FROM enrollments WHERE id = p_enrollment_id;
    END delete_enrollment;

    -- Add new program
    PROCEDURE add_program(
        p_name        IN VARCHAR2,
        p_description IN VARCHAR2,
        p_duration    IN VARCHAR2,
        p_program_id  OUT NUMBER
    ) AS
    BEGIN
        INSERT INTO programs(name, description, duration)
        VALUES (p_name, p_description, p_duration)
        RETURNING id INTO p_program_id;
    END add_program;

    -- Update program
    PROCEDURE update_program(
        p_program_id  IN NUMBER,
        p_name        IN VARCHAR2,
        p_description IN VARCHAR2,
        p_duration    IN VARCHAR2
    ) AS
    BEGIN
        UPDATE programs
        SET name        = p_name,
            description = p_description,
            duration    = p_duration
        WHERE id = p_program_id;
    END update_program;

    -- Delete program
    PROCEDURE delete_program(p_program_id IN NUMBER) AS
    BEGIN
        DELETE FROM programs WHERE id = p_program_id;
    END delete_program;

    -- Get all programs
    PROCEDURE get_programs(p_cursor OUT SYS_REFCURSOR) AS
    BEGIN
        OPEN p_cursor FOR
            SELECT id, name, description, duration
            FROM programs
            ORDER BY id;
    END get_programs;

END pkg_student_enroll;
/
---- create package enrollemnts ----------
CREATE OR REPLACE PACKAGE pkg_enrollment AS
  PROCEDURE add_student(
    p_fullname IN VARCHAR2,
    p_dob IN DATE,
    p_gender IN VARCHAR2,
    p_phone IN VARCHAR2,
    p_address IN VARCHAR2
  );
  
  PROCEDURE add_program(
    p_name IN VARCHAR2,
    p_description IN VARCHAR2,
    p_duration IN VARCHAR2
  );

  PROCEDURE enroll_student(
    p_student_id IN NUMBER,
    p_program_id IN NUMBER,
    p_enroll_date IN DATE
  );
END pkg_enrollment;
/
CREATE OR REPLACE PACKAGE BODY pkg_enrollment AS
  PROCEDURE add_student(
    p_fullname IN VARCHAR2,
    p_dob IN DATE,
    p_gender IN VARCHAR2,
    p_phone IN VARCHAR2,
    p_address IN VARCHAR2
  ) IS
  BEGIN
    INSERT INTO students(full_name, dob, gender, phone, address)
    VALUES (p_fullname, p_dob, p_gender, p_phone, p_address);
  END;

PROCEDURE add_program(
    p_name IN VARCHAR2,
    p_description IN VARCHAR2,
    p_duration IN VARCHAR2
  ) IS
  BEGIN
    INSERT INTO programs(name, description, duration)
    VALUES (p_name, p_description, p_duration);
  END;

  PROCEDURE enroll_student(
    p_student_id IN NUMBER,
    p_program_id IN NUMBER,
    p_enroll_date IN DATE
  ) IS
  BEGIN
    INSERT INTO enrollments(student_id, program_id, enrollment_date)
    VALUES (p_student_id, p_program_id, p_enroll_date);
  END;
END pkg_enrollment;
/
--- insert student 10 record
BEGIN
  pkg_enrollment.add_student('Alice Chan', DATE '2001-02-14', 'Female', '010111222', 'Phnom Penh');
  pkg_enrollment.add_student('Bora Lim', DATE '2000-05-10', 'Male', '010222333', 'Siem Reap');
  pkg_enrollment.add_student('Chenda Sok', DATE '2002-03-19', 'Female', '010333444', 'Battambang');
  pkg_enrollment.add_student('David Kim', DATE '2001-08-23', 'Male', '010444555', 'Takeo');
  pkg_enrollment.add_student('Eang Vuthy', DATE '1999-12-30', 'Male', '010555666', 'Kampot');
  pkg_enrollment.add_student('Fiona Sun', DATE '2003-06-11', 'Female', '010666777', 'Kandal');
  pkg_enrollment.add_student('Gavin Yin', DATE '2001-09-09', 'Male', '010777888', 'Kompot');
  pkg_enrollment.add_student('Hana Meas', DATE '2000-01-01', 'Female', '010888999', 'Banteay Meanchey');
  pkg_enrollment.add_student('Ith Dara', DATE '2002-10-18', 'Male', '010999000', 'Kampong Cham');
  pkg_enrollment.add_student('Julie Heng', DATE '2003-11-25', 'Female', '011111222', 'Kep');
END;
/
-- insert program 10 record
BEGIN
  pkg_enrollment.add_program('Computer Science', 'Learn programming and algorithms', '4 Years');
  pkg_enrollment.add_program('Information Technology', 'Network and IT infrastructure', '4 Years');
  pkg_enrollment.add_program('Business Management', 'Leadership and management principles', '3 Years');
  pkg_enrollment.add_program('Accounting', 'Financial reporting and auditing', '3 Years');
  pkg_enrollment.add_program('Marketing', 'Digital and traditional marketing', '3 Years');
  pkg_enrollment.add_program('Graphic Design', 'Creative and visual design', '3 Years');
  pkg_enrollment.add_program('Tourism', 'Travel and hospitality management', '3 Years');
  pkg_enrollment.add_program('Law', 'Legal studies and practice', '4 Years');
  pkg_enrollment.add_program('Civil Engineering', 'Design and construction fundamentals', '4 Years');
  pkg_enrollment.add_program('English Literature', 'Language and literary analysis', '3 Years');
END;
/

begin
pkg_student_enroll.get_programs();
end;

select * from students;
select * from programs;

-- run get program
DECLARE
    v_cursor SYS_REFCURSOR;
    v_id NUMBER;
    v_name VARCHAR2(100);
    v_description VARCHAR2(100);
    v_duration VARCHAR2(50);
BEGIN
    pkg_student_enroll.get_programs(v_cursor);

    LOOP
        FETCH v_cursor INTO v_id, v_name, v_description, v_duration;
        EXIT WHEN v_cursor%NOTFOUND;
        DBMS_OUTPUT.PUT_LINE('Program ID: ' || v_id || ', Name: ' || v_name || ', Duration: ' || v_duration);
    END LOOP;

    CLOSE v_cursor;
END;
/


DECLARE
    v_program_id NUMBER;
BEGIN
    pkg_student_enroll.add_program(
        p_name        => 'Computer Science',
        p_description => 'CS Degree Program',
        p_duration    => '4 years',
        p_program_id  => v_program_id
    );
    DBMS_OUTPUT.PUT_LINE('New Program ID: ' || v_program_id);
END;
/
select * from programs;
